In [116]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import os
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.cluster import KMeans
%matplotlib inline
from sklearn.preprocessing import StandardScaler
import warnings
warnings.simplefilter('ignore')
import numpy as np


In [117]:
housing_training_data = pd.read_csv("housing_training_data.csv")
housing_training_data.head()

house_id     price  beds  baths  square_feet  lot_size  hoa_permonth  \
0         1  369900.0   5.0    3.0       2500.0  404672.0           0.0   
1         2  319000.0   2.0    2.0       1456.0  125452.0           0.0   
2         3  115000.0   2.0    1.0        896.0   86248.0           0.0   
3         4  205000.0   3.0    1.0       1423.0   78408.0           0.0   
4         5  299000.0   2.0    2.0       2185.0   78843.0           0.0   

   Summer Temp  Winter Temp  population  
0         61.0         19.0      1930.0  
1         61.0         19.0      1930.0  
2         61.0         19.0      1930.0  
3         61.0         19.0      1930.0  
4         61.0         19.0      1930.0

In [118]:
house_data_for_results = pd.read_csv("combination_data/housing_complete_data.csv")
house_data_for_results.head()

Unnamed: 0  house_id              property_type                address  \
0           0         1  Single Family Residential  32996 Heather Glen Ct   
1           1         2  Single Family Residential      70875 Lee Roy Ave   
2           2         3  Single Family Residential     26890 Sterling Hwy   
3           3         4  Single Family Residential     31513 Sterling Hwy   
4           4         5  Single Family Residential        72960 Laida Ave   

           city state zip_code     price  beds  baths  ...  lot_size  \
0  Anchor Point    AK  99556.0  369900.0   5.0    3.0  ...  404672.0   
1  Anchor Point    AK  99556.0  319000.0   2.0    2.0  ...  125452.0   
2  Anchor Point    AK  99556.0  115000.0   2.0    1.0  ...   86248.0   
3  Anchor Point    AK  99556.0  205000.0   3.0    1.0  ...   78408.0   
4  Anchor Point    AK  99556.0  299000.0   2.0    2.0  ...   78843.0   

   year_built hoa_permonth                                                url  \
0      2016.0          0.0  http://www.redfin.com/AK/Unknown/32996-HEATHER...   
1      2002.0          0.0  http://www.redfin.com/AK/Anchor-Point/70875-Le...   
2      2009.0          0.0  http://www.redfin.com/AK/Anchor-Point/26890-St...   
3      1962.0          0.0  http://www.redfin.com/AK/Anchor-Point/31513-St...   
4      1998.0          0.0  http://www.redfin.com/AK/Anchor-Point/72960-La...   

    latitude   longitude  Summer Temp  Winter Temp  population  pop_cat  
0  59.794550 -151.827787         61.0         19.0      1930.0    small  
1  59.845004 -151.787534         61.0         19.0      1930.0    small  
2  59.882706 -151.782732         61.0         19.0      1930.0    small  
3  59.816224 -151.827229         61.0         19.0      1930.0    small  
4  59.781840 -151.851596         61.0         19.0      1930.0    small  

[5 rows x 21 columns]

In [119]:
X = housing_training_data[['price', "beds", 'baths', "square_feet", "lot_size", 'hoa_permonth', "Summer Temp", "Winter Temp", "population"
                          ]]
print(X.shape)

(10027, 9)


In [120]:
X.head(100)

price  beds  baths  square_feet  lot_size  hoa_permonth  Summer Temp  \
0   369900.0   5.0    3.0       2500.0  404672.0           0.0         61.0   
1   319000.0   2.0    2.0       1456.0  125452.0           0.0         61.0   
2   115000.0   2.0    1.0        896.0   86248.0           0.0         61.0   
3   205000.0   3.0    1.0       1423.0   78408.0           0.0         61.0   
4   299000.0   2.0    2.0       2185.0   78843.0           0.0         61.0   
..       ...   ...    ...          ...       ...           ...          ...   
95  319900.0   3.0    2.0       1728.0    8416.0           0.0         62.7   
96  430000.0   8.0    4.0       3264.0    6534.0           0.0         62.7   
97  239900.0   2.0    2.0       1300.0    6250.0           0.0         62.7   
98  338500.0   4.0    2.0       1898.0    8591.0           0.0         62.7   
99  338900.0   5.0    2.0       2112.0   11500.0           0.0         62.7   

    Winter Temp  population  
0          19.0      1930.0  
1          19.0      1930.0  
2          19.0      1930.0  
3          19.0      1930.0  
4          19.0      1930.0  
..          ...         ...  
95         20.4    291826.0  
96         20.4    291826.0  
97         20.4    291826.0  
98         20.4    291826.0  
99         20.4    291826.0  

[100 rows x 9 columns]

In [121]:
data = X.copy()

In [122]:
from sklearn.model_selection import train_test_split

X_train, X_test= train_test_split(X, random_state=42)

X_train.head()

price  beds  baths  square_feet  lot_size  hoa_permonth  \
3827  2348888.0   4.0    2.0       2420.0    2604.0           0.0   
9498   369900.0   2.0    1.0        831.0    7500.0         440.0   
1506   368330.0   5.0    3.5       2898.0   10890.0          54.0   
7684   400000.0   0.0    0.0       3290.0   14810.0           0.0   
3288   824900.0   3.0    2.5       1661.0   10288.0           0.0   

      Summer Temp  Winter Temp  population  
3827         67.2         54.0    805235.0  
9498         69.1         45.0    608660.0  
1506         89.0         28.0      5281.0  
7684         94.3         50.3    583756.0  
3288         76.0         49.0   1307402.0

In [123]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X)


In [124]:
X_train_scaled = X_scaler.transform(X)
X_scaled


array([[-0.37052864,  0.90686563,  0.35279982, ..., -1.9178473 ,
        -1.39097322, -0.60011618],
       [-0.41673656, -0.47088311, -0.1950377 , ..., -1.9178473 ,
        -1.39097322, -0.60011618],
       [-0.60193135, -0.47088311, -0.74287521, ..., -1.9178473 ,
        -1.39097322, -0.60011618],
       ...,
       [-0.16254762, -0.01163353, -0.74287521, ..., -1.06404396,
         0.43443371, -0.54973089],
       [-0.37497695, -0.01163353, -0.1950377 , ..., -0.02050654,
        -0.40806179, -0.44242011],
       [-0.37497695, -0.01163353, -0.1950377 , ..., -0.02050654,
        -0.40806179, -0.44242011]])

In [186]:
kmeans = KMeans(n_clusters=200)

In [187]:
kmeans.fit(X)


KMeans(n_clusters=200)

In [188]:
predicted_clusters = kmeans.predict(X)

In [189]:
X

price  beds  baths  square_feet  lot_size  hoa_permonth  \
0      369900.0   5.0   3.00       2500.0  404672.0           0.0   
1      319000.0   2.0   2.00       1456.0  125452.0           0.0   
2      115000.0   2.0   1.00        896.0   86248.0           0.0   
3      205000.0   3.0   1.00       1423.0   78408.0           0.0   
4      299000.0   2.0   2.00       2185.0   78843.0           0.0   
...         ...   ...    ...          ...       ...           ...   
10022  515000.0   2.0   2.25       1420.0    1245.0         190.0   
10023  599000.0   3.0   1.00       1020.0    6135.0           0.0   
10024  599000.0   3.0   1.00       1020.0    6135.0           0.0   
10025  365000.0   3.0   2.00       1324.0       0.0         237.0   
10026  365000.0   3.0   2.00       1324.0       0.0         237.0   

       Summer Temp  Winter Temp  population  
0             61.0         19.0      1930.0  
1             61.0         19.0      1930.0  
2             61.0         19.0      1930.0  
3             61.0         19.0      1930.0  
4             61.0         19.0      1930.0  
...            ...          ...         ...  
10022         69.1         45.0    608660.0  
10023         69.1         45.0     53007.0  
10024         69.1         45.0     53007.0  
10025         79.0         33.0    161791.0  
10026         79.0         33.0    161791.0  

[10027 rows x 9 columns]

In [190]:
Xlist = X.to_numpy()

In [191]:
Xlist

array([[3.69900e+05, 5.00000e+00, 3.00000e+00, ..., 6.10000e+01,
        1.90000e+01, 1.93000e+03],
       [3.19000e+05, 2.00000e+00, 2.00000e+00, ..., 6.10000e+01,
        1.90000e+01, 1.93000e+03],
       [1.15000e+05, 2.00000e+00, 1.00000e+00, ..., 6.10000e+01,
        1.90000e+01, 1.93000e+03],
       ...,
       [5.99000e+05, 3.00000e+00, 1.00000e+00, ..., 6.91000e+01,
        4.50000e+01, 5.30070e+04],
       [3.65000e+05, 3.00000e+00, 2.00000e+00, ..., 7.90000e+01,
        3.30000e+01, 1.61791e+05],
       [3.65000e+05, 3.00000e+00, 2.00000e+00, ..., 7.90000e+01,
        3.30000e+01, 1.61791e+05]])

### HERE BEGINS THE MAGIC

In [192]:
kmeans.fit(Xlist)

predicted_clusters = kmeans.predict(Xlist)
#TESTING INFO INPUT BLAH BLAH
# predicted_clusters = [this is where we put the array of inputed data]

In [193]:
predicted_clusters

array([199, 187, 105, ...,  76,   4,   4], dtype=int32)

In [194]:
# Plot the clusters
# plt.scatter(Xlist[:, 0], Xlist[:, 1], c=predicted_clusters, s=50, cmap='viridis')
# plt.show()

In [195]:
# Print the cluster centers and cluster labels
centers = kmeans.cluster_centers_
labels = kmeans.labels_

In [196]:
centers

array([[1.12631613e+06, 1.90322581e+00, 1.46774194e+00, ...,
        6.72000000e+01, 5.40000000e+01, 8.05235000e+05],
       [3.05755556e+05, 1.22222222e+00, 8.88888889e-01, ...,
        7.90000000e+01, 5.10000000e+01, 3.79262100e+06],
       [1.49950000e+07, 5.00000000e+00, 4.50000000e+00, ...,
        7.90000000e+01, 5.10000000e+01, 3.79262100e+06],
       ...,
       [1.90642857e+06, 2.57142857e+00, 2.07142857e+00, ...,
        7.55000000e+01, 3.26000000e+01, 8.17513300e+06],
       [8.71000000e+04, 1.42857143e-01, 1.42857143e-01, ...,
        8.33809524e+01, 3.09047619e+01, 2.05983667e+05],
       [2.74421000e+05, 2.89473684e+00, 2.05263158e+00, ...,
        6.77894737e+01, 1.63157895e+01, 7.92247368e+03]])

In [197]:
# plt.scatter(Xlist[:, 0], Xlist[:, 1], c=labels, s=50, cmap='viridis')
# plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5)

# plt.show()

In [198]:
cat = kmeans.predict(Xlist[0].reshape(1, -1))

In [199]:
Xlist[0]

array([3.69900e+05, 5.00000e+00, 3.00000e+00, 2.50000e+03, 4.04672e+05,
       0.00000e+00, 6.10000e+01, 1.90000e+01, 1.93000e+03])

In [200]:
Xlist[1]

array([3.19000e+05, 2.00000e+00, 2.00000e+00, 1.45600e+03, 1.25452e+05,
       0.00000e+00, 6.10000e+01, 1.90000e+01, 1.93000e+03])

In [201]:
X

price  beds  baths  square_feet  lot_size  hoa_permonth  \
0      369900.0   5.0   3.00       2500.0  404672.0           0.0   
1      319000.0   2.0   2.00       1456.0  125452.0           0.0   
2      115000.0   2.0   1.00        896.0   86248.0           0.0   
3      205000.0   3.0   1.00       1423.0   78408.0           0.0   
4      299000.0   2.0   2.00       2185.0   78843.0           0.0   
...         ...   ...    ...          ...       ...           ...   
10022  515000.0   2.0   2.25       1420.0    1245.0         190.0   
10023  599000.0   3.0   1.00       1020.0    6135.0           0.0   
10024  599000.0   3.0   1.00       1020.0    6135.0           0.0   
10025  365000.0   3.0   2.00       1324.0       0.0         237.0   
10026  365000.0   3.0   2.00       1324.0       0.0         237.0   

       Summer Temp  Winter Temp  population  
0             61.0         19.0      1930.0  
1             61.0         19.0      1930.0  
2             61.0         19.0      1930.0  
3             61.0         19.0      1930.0  
4             61.0         19.0      1930.0  
...            ...          ...         ...  
10022         69.1         45.0    608660.0  
10023         69.1         45.0     53007.0  
10024         69.1         45.0     53007.0  
10025         79.0         33.0    161791.0  
10026         79.0         33.0    161791.0  

[10027 rows x 9 columns]

In [202]:
house_list = []

for i in range(4000):
    if kmeans.predict(Xlist[i].reshape(1, -1)) == cat:
        print (housing_training_data.iloc[i])
        print (housing_training_data.house_id[i])
        house_list.append(housing_training_data.house_id[i])
        print (Xlist[i])
        print (kmeans.predict(Xlist[i].reshape(1, -1)))
        
    

house_id             1.0
price           369900.0
beds                 5.0
baths                3.0
square_feet       2500.0
lot_size        404672.0
hoa_permonth         0.0
Summer Temp         61.0
Winter Temp         19.0
population        1930.0
Name: 0, dtype: float64
1
[3.69900e+05 5.00000e+00 3.00000e+00 2.50000e+03 4.04672e+05 0.00000e+00
 6.10000e+01 1.90000e+01 1.93000e+03]
[199]
house_id             6.0
price           369000.0
beds                 4.0
baths                2.0
square_feet       2945.0
lot_size        384199.0
hoa_permonth         0.0
Summer Temp         61.0
Winter Temp         19.0
population        1930.0
Name: 5, dtype: float64
6
[3.69000e+05 4.00000e+00 2.00000e+00 2.94500e+03 3.84199e+05 0.00000e+00
 6.10000e+01 1.90000e+01 1.93000e+03]
[199]
house_id            12.0
price           324000.0
beds                 3.0
baths                3.0
square_feet       2824.0
lot_size        336283.0
hoa_permonth         0.0
Summer Temp         61.0
Winter Temp   

In [203]:
house_list

[1,
 6,
 12,
 15,
 16,
 27,
 364,
 563,
 660,
 728,
 804,
 825,
 854,
 888,
 956,
 1025,
 1168,
 1453,
 2164]

In [204]:
# now we go back to the orginal dataframe and find these house_ids
# df.loc[df['column_name'] == some_value]
# find_it = house_data_for_results.loc[housing_training_data['house_id'] == 1]

In [205]:
# find_it

In [206]:
# print(f'{find_it.house_id} and {find_it.price}'" in the US.")

In [207]:
# for row in housing_training_data.itertuples():
# #     if (housing_training_data.house_id == "1"):
#     print(row)

In [208]:
house_data_for_results.head()

Unnamed: 0  house_id              property_type                address  \
0           0         1  Single Family Residential  32996 Heather Glen Ct   
1           1         2  Single Family Residential      70875 Lee Roy Ave   
2           2         3  Single Family Residential     26890 Sterling Hwy   
3           3         4  Single Family Residential     31513 Sterling Hwy   
4           4         5  Single Family Residential        72960 Laida Ave   

           city state zip_code     price  beds  baths  ...  lot_size  \
0  Anchor Point    AK  99556.0  369900.0   5.0    3.0  ...  404672.0   
1  Anchor Point    AK  99556.0  319000.0   2.0    2.0  ...  125452.0   
2  Anchor Point    AK  99556.0  115000.0   2.0    1.0  ...   86248.0   
3  Anchor Point    AK  99556.0  205000.0   3.0    1.0  ...   78408.0   
4  Anchor Point    AK  99556.0  299000.0   2.0    2.0  ...   78843.0   

   year_built hoa_permonth                                                url  \
0      2016.0          0.0  http://www.redfin.com/AK/Unknown/32996-HEATHER...   
1      2002.0          0.0  http://www.redfin.com/AK/Anchor-Point/70875-Le...   
2      2009.0          0.0  http://www.redfin.com/AK/Anchor-Point/26890-St...   
3      1962.0          0.0  http://www.redfin.com/AK/Anchor-Point/31513-St...   
4      1998.0          0.0  http://www.redfin.com/AK/Anchor-Point/72960-La...   

    latitude   longitude  Summer Temp  Winter Temp  population  pop_cat  
0  59.794550 -151.827787         61.0         19.0      1930.0    small  
1  59.845004 -151.787534         61.0         19.0      1930.0    small  
2  59.882706 -151.782732         61.0         19.0      1930.0    small  
3  59.816224 -151.827229         61.0         19.0      1930.0    small  
4  59.781840 -151.851596         61.0         19.0      1930.0    small  

[5 rows x 21 columns]

In [209]:
# house_list_test =  [1, 13, 43, 5643,357, 999]


In [210]:
results_df = house_data_for_results[house_data_for_results["house_id"].isin(house_list)]
results_df

Unnamed: 0  house_id              property_type                address  \
0              0         1  Single Family Residential  32996 Heather Glen Ct   
5              5         6  Single Family Residential       71185 Kutafya Rd   
11            11        12  Single Family Residential     26957 Sterling Hwy   
14            14        15  Single Family Residential       28160 Chestes Rd   
15            15        16  Single Family Residential    34614 North Fork Rd   
26            26        27  Single Family Residential        27155 Cloyds Rd   
363          363       364  Single Family Residential       38929 Alathea St   
562          562       563  Single Family Residential          14845 Lobo Ln   
659          659       660  Single Family Residential  10703 S Old Glenn Hwy   
727          727       728  Single Family Residential         35250 James St   
803          803       804  Single Family Residential      38061 Tim Ross Rd   
824          824       825  Single Family Residential      26129 N Glenn Hwy   
853          853       854  Single Family Residential    1981 E Holobinko Rd   
887          887       888  Single Family Residential        2769 E Coles Rd   
955          955       956  Single Family Residential        3951 Wyoming Dr   
1024        1024      1025  Single Family Residential   25445 Landlocked Ave   
1167        1167      1168  Single Family Residential   164 Naval Reserve Rd   
1452        1452      1453  Single Family Residential    5051 Old Moulton Rd   
2163        2163      2164  Single Family Residential    7854 Old Dixiana Rd   

              city state zip_code     price  beds  baths  ...  lot_size  \
0     Anchor Point    AK  99556.0  369900.0   5.0    3.0  ...  404672.0   
5     Anchor Point    AK  99556.0  369000.0   4.0    2.0  ...  384199.0   
11    Anchor Point    AK  99556.0  324000.0   3.0    3.0  ...  336283.0   
14    Anchor Point    AK  99556.0  324900.0   7.0    8.0  ...  394218.0   
15    Anchor Point    AK  99556.0  339500.0   1.0    1.0  ...  479160.0   
26    Anchor Point    AK  99556.0  204000.0   1.0    1.0  ...  470448.0   
363          Homer    AK  99603.0  310000.0   1.0    0.0  ...  316245.0   
562      Ninilchik    AK  99639.0  149500.0   2.0    1.0  ...  486129.0   
659         Palmer    AK  99645.0  324900.0   9.0    4.0  ...  409464.0   
727       Soldotna    AK  99669.0  189000.0   1.0    1.0  ...  395089.0   
803       Sterling    AK  99672.0  239000.0   2.0    2.0  ...  374616.0   
824         Sutton    AK  99674.0  375000.0   3.0    2.0  ...  525769.0   
853        Wasilla    AK  99654.0  315000.0   1.0    1.0  ...  434293.0   
887        Wasilla    AK  99654.0  374999.0   2.0    2.0  ...  417740.0   
955        Wasilla    AK  99623.0  371000.0   3.0    2.0  ...  423404.0   
1024        Willow    AK  99688.0   99500.0   2.0    1.0  ...  377665.0   
1167      Bessemer    AL    35023  234900.0   3.0    2.0  ...  479160.0   
1452       Decatur    AL    35603  179900.0   3.0    1.0  ...  479160.0   
2163        Pinson    AL    35123  120000.0   2.0    2.0  ...  435600.0   

      year_built hoa_permonth  \
0         2016.0          0.0   
5         1983.0          0.0   
11        1986.0          0.0   
14        2002.0          0.0   
15        1994.0          0.0   
26        1999.0          0.0   
363       1999.0          0.0   
562       1990.0          0.0   
659       1966.0          0.0   
727       1985.0          0.0   
803       2008.0          0.0   
824       1972.0          0.0   
853       1975.0          0.0   
887       1993.0          0.0   
955       2020.0          0.0   
1024      2016.0          0.0   
1167      1930.0          0.0   
1452      1958.0          0.0   
2163      1965.0          0.0   

                                                    url   latitude  \
0     http://www.redfin.com/AK/Unknown/32996-HEATHER...  59.794550   
5     http://www.redfin.com/AK/Anchor-Point/71185-Ku...  59.837067   
11    http://www.redfin.com/AK/An

In [115]:
results_df.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Unnamed: 0</th>\n      <th>house_id</th>\n      <th>property_type</th>\n      <th>address</th>\n      <th>city</th>\n      <th>state</th>\n      <th>zip_code</th>\n      <th>price</th>\n      <th>beds</th>\n      <th>baths</th>\n      <th>square_feet</th>\n      <th>lot_size</th>\n      <th>year_built</th>\n      <th>hoa_permonth</th>\n      <th>url</th>\n      <th>latitude</th>\n      <th>longitude</th>\n      <th>Summer Temp</th>\n      <th>Winter Temp</th>\n      <th>population</th>\n      <th>pop_cat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>1</td>\n      <td>Single Family Residential</td>\n      <td>32996 Heather Glen Ct</td>\n      <td>Anchor Point</td>\n      <td>AK</td>\n      <td>99556.0</td>\n      <td>369900.0</td>\n      <td>5.0</td>\n      <td>3.00</td>\n      <td>2500.0</td>\n      <td>404672.0</td>\n      