In [12]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import os
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.cluster import KMeans
%matplotlib inline
from sklearn.preprocessing import StandardScaler
import warnings
warnings.simplefilter('ignore')
import numpy as np


In [13]:
housing_training_data = pd.read_csv("housing_training_data.csv")
housing_training_data.head()

house_id     price  beds  baths  square_feet  lot_size  hoa_permonth  \
0         1  369900.0   5.0    3.0       2500.0  404672.0           0.0   
1         2  319000.0   2.0    2.0       1456.0  125452.0           0.0   
2         3  115000.0   2.0    1.0        896.0   86248.0           0.0   
3         4  205000.0   3.0    1.0       1423.0   78408.0           0.0   
4         5  299000.0   2.0    2.0       2185.0   78843.0           0.0   

   Summer Temp  Winter Temp  population  
0         61.0         19.0      1930.0  
1         61.0         19.0      1930.0  
2         61.0         19.0      1930.0  
3         61.0         19.0      1930.0  
4         61.0         19.0      1930.0

In [14]:
house_data_for_results = pd.read_csv("combination_data/housing_complete_data.csv")
house_data_for_results.head()

Unnamed: 0  house_id              property_type                address  \
0           0         1  Single Family Residential  32996 Heather Glen Ct   
1           1         2  Single Family Residential      70875 Lee Roy Ave   
2           2         3  Single Family Residential     26890 Sterling Hwy   
3           3         4  Single Family Residential     31513 Sterling Hwy   
4           4         5  Single Family Residential        72960 Laida Ave   

           city state zip_code     price  beds  baths  ...  lot_size  \
0  Anchor Point    AK  99556.0  369900.0   5.0    3.0  ...  404672.0   
1  Anchor Point    AK  99556.0  319000.0   2.0    2.0  ...  125452.0   
2  Anchor Point    AK  99556.0  115000.0   2.0    1.0  ...   86248.0   
3  Anchor Point    AK  99556.0  205000.0   3.0    1.0  ...   78408.0   
4  Anchor Point    AK  99556.0  299000.0   2.0    2.0  ...   78843.0   

   year_built hoa_permonth                                                url  \
0      2016.0          0.0  http://www.redfin.com/AK/Unknown/32996-HEATHER...   
1      2002.0          0.0  http://www.redfin.com/AK/Anchor-Point/70875-Le...   
2      2009.0          0.0  http://www.redfin.com/AK/Anchor-Point/26890-St...   
3      1962.0          0.0  http://www.redfin.com/AK/Anchor-Point/31513-St...   
4      1998.0          0.0  http://www.redfin.com/AK/Anchor-Point/72960-La...   

    latitude   longitude  Summer Temp  Winter Temp  population  pop_cat  
0  59.794550 -151.827787         61.0         19.0      1930.0    small  
1  59.845004 -151.787534         61.0         19.0      1930.0    small  
2  59.882706 -151.782732         61.0         19.0      1930.0    small  
3  59.816224 -151.827229         61.0         19.0      1930.0    small  
4  59.781840 -151.851596         61.0         19.0      1930.0    small  

[5 rows x 21 columns]

In [15]:
X = housing_training_data[['price', "beds", 'baths', "square_feet", "lot_size", 'hoa_permonth', "Summer Temp", "Winter Temp", "population"
                          ]]
print(X.shape)

(12223, 9)


In [16]:
X.head(100)

price  beds  baths  square_feet  lot_size  hoa_permonth  Summer Temp  \
0   369900.0   5.0    3.0       2500.0  404672.0           0.0         61.0   
1   319000.0   2.0    2.0       1456.0  125452.0           0.0         61.0   
2   115000.0   2.0    1.0        896.0   86248.0           0.0         61.0   
3   205000.0   3.0    1.0       1423.0   78408.0           0.0         61.0   
4   299000.0   2.0    2.0       2185.0   78843.0           0.0         61.0   
..       ...   ...    ...          ...       ...           ...          ...   
95  338900.0   5.0    2.0       2112.0   11500.0           0.0         62.7   
96  725000.0   3.0    4.0       3194.0   40887.0           0.0         62.7   
97  189000.0   3.0    2.0       1060.0    9025.0           0.0         62.7   
98  439900.0   3.0    2.0       2710.0    9495.0           0.0         62.7   
99  575000.0  17.0    8.0       4560.0   15000.0           0.0         62.7   

    Winter Temp  population  
0          19.0      1930.0  
1          19.0      1930.0  
2          19.0      1930.0  
3          19.0      1930.0  
4          19.0      1930.0  
..          ...         ...  
95         20.4    291826.0  
96         20.4    291826.0  
97         20.4    291826.0  
98         20.4    291826.0  
99         20.4    291826.0  

[100 rows x 9 columns]

In [17]:
data = X.copy()

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test= train_test_split(X, random_state=42)

X_train.head()

price  beds  baths  square_feet  lot_size  hoa_permonth  \
2138    345000.0   3.0    2.5       2658.0  169884.0           0.0   
10223  1075000.0   2.0    1.5          0.0       0.0           0.0   
4226    270000.0   4.0    2.5       1796.0    1177.0         100.0   
742     710000.0   3.0    3.0       1660.0  174240.0           0.0   
8139   1350000.0   3.0    3.5       2525.0       0.0        1663.0   

       Summer Temp  Winter Temp  population  
2138          82.0         45.0     19933.0  
10223         75.5         32.6   2533000.0  
4226         104.0         46.0      1426.0  
742           65.0          6.0      7831.0  
8139          84.1         68.6    399457.0

In [19]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X)


In [20]:
X_train_scaled = X_scaler.transform(X)



In [21]:
kmeans = KMeans(n_clusters=200)

In [22]:
kmeans.fit(X)


KMeans(n_clusters=200)

In [23]:
predicted_clusters = kmeans.predict(X)

In [24]:
X

price  beds  baths  square_feet  lot_size  hoa_permonth  \
0      369900.0   5.0   3.00       2500.0  404672.0           0.0   
1      319000.0   2.0   2.00       1456.0  125452.0           0.0   
2      115000.0   2.0   1.00        896.0   86248.0           0.0   
3      205000.0   3.0   1.00       1423.0   78408.0           0.0   
4      299000.0   2.0   2.00       2185.0   78843.0           0.0   
...         ...   ...    ...          ...       ...           ...   
12218  515000.0   2.0   2.25       1420.0    1245.0         190.0   
12219  599000.0   3.0   1.00       1020.0    6135.0           0.0   
12220  599000.0   3.0   1.00       1020.0    6135.0           0.0   
12221  365000.0   3.0   2.00       1324.0       0.0         237.0   
12222  365000.0   3.0   2.00       1324.0       0.0         237.0   

       Summer Temp  Winter Temp  population  
0             61.0         19.0      1930.0  
1             61.0         19.0      1930.0  
2             61.0         19.0      1930.0  
3             61.0         19.0      1930.0  
4             61.0         19.0      1930.0  
...            ...          ...         ...  
12218         77.0         36.3    608660.0  
12219         65.4         40.6     53007.0  
12220         65.4         40.6     53007.0  
12221         69.1         45.0    161791.0  
12222         69.1         45.0    161791.0  

[12223 rows x 9 columns]

In [25]:
Xlist = X.to_numpy()

In [26]:
Xlist

array([[3.69900e+05, 5.00000e+00, 3.00000e+00, ..., 6.10000e+01,
        1.90000e+01, 1.93000e+03],
       [3.19000e+05, 2.00000e+00, 2.00000e+00, ..., 6.10000e+01,
        1.90000e+01, 1.93000e+03],
       [1.15000e+05, 2.00000e+00, 1.00000e+00, ..., 6.10000e+01,
        1.90000e+01, 1.93000e+03],
       ...,
       [5.99000e+05, 3.00000e+00, 1.00000e+00, ..., 6.54000e+01,
        4.06000e+01, 5.30070e+04],
       [3.65000e+05, 3.00000e+00, 2.00000e+00, ..., 6.91000e+01,
        4.50000e+01, 1.61791e+05],
       [3.65000e+05, 3.00000e+00, 2.00000e+00, ..., 6.91000e+01,
        4.50000e+01, 1.61791e+05]])

### HERE BEGINS THE MAGIC

In [27]:
kmeans.fit(Xlist)

predicted_clusters = kmeans.predict(Xlist)
#TESTING INFO INPUT BLAH BLAH
# predicted_clusters = [this is where we put the array of inputed data]

In [28]:
predicted_clusters

array([131, 146,  40, ...,  48, 126, 126], dtype=int32)

In [29]:
# Plot the clusters
# plt.scatter(Xlist[:, 0], Xlist[:, 1], c=predicted_clusters, s=50, cmap='viridis')
# plt.show()

In [30]:
# Print the cluster centers and cluster labels
centers = kmeans.cluster_centers_
labels = kmeans.labels_

In [31]:
centers

array([[4.03749000e+05, 2.92156863e+00, 2.25000000e+00, ...,
        7.42137255e+01, 2.84882353e+01, 2.38669608e+04],
       [1.64122211e+06, 4.88888889e+00, 3.16666667e+00, ...,
        7.90000000e+01, 5.10000000e+01, 3.79262100e+06],
       [7.50000000e+06, 2.40000000e+01, 0.00000000e+00, ...,
        6.72000000e+01, 5.40000000e+01, 8.05235000e+05],
       ...,
       [1.55814930e+05, 2.23478261e+00, 1.54130435e+00, ...,
        9.26591304e+01, 4.68660870e+01, 1.78183339e+05],
       [3.52067495e+06, 4.80000000e+00, 5.55000000e+00, ...,
        9.00100000e+01, 3.81750000e+01, 6.49286500e+04],
       [5.26752941e+05, 2.23529412e+00, 1.32352941e+00, ...,
        7.90000000e+01, 5.10000000e+01, 3.79262100e+06]])

In [32]:
# plt.scatter(Xlist[:, 0], Xlist[:, 1], c=labels, s=50, cmap='viridis')
# plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5)

# plt.show()

In [33]:
cat = kmeans.predict(Xlist[0].reshape(1, -1))

In [34]:
Xlist[0]

array([3.69900e+05, 5.00000e+00, 3.00000e+00, 2.50000e+03, 4.04672e+05,
       0.00000e+00, 6.10000e+01, 1.90000e+01, 1.93000e+03])

In [35]:
Xlist[1]

array([3.19000e+05, 2.00000e+00, 2.00000e+00, 1.45600e+03, 1.25452e+05,
       0.00000e+00, 6.10000e+01, 1.90000e+01, 1.93000e+03])

In [36]:
X

price  beds  baths  square_feet  lot_size  hoa_permonth  \
0      369900.0   5.0   3.00       2500.0  404672.0           0.0   
1      319000.0   2.0   2.00       1456.0  125452.0           0.0   
2      115000.0   2.0   1.00        896.0   86248.0           0.0   
3      205000.0   3.0   1.00       1423.0   78408.0           0.0   
4      299000.0   2.0   2.00       2185.0   78843.0           0.0   
...         ...   ...    ...          ...       ...           ...   
12218  515000.0   2.0   2.25       1420.0    1245.0         190.0   
12219  599000.0   3.0   1.00       1020.0    6135.0           0.0   
12220  599000.0   3.0   1.00       1020.0    6135.0           0.0   
12221  365000.0   3.0   2.00       1324.0       0.0         237.0   
12222  365000.0   3.0   2.00       1324.0       0.0         237.0   

       Summer Temp  Winter Temp  population  
0             61.0         19.0      1930.0  
1             61.0         19.0      1930.0  
2             61.0         19.0      1930.0  
3             61.0         19.0      1930.0  
4             61.0         19.0      1930.0  
...            ...          ...         ...  
12218         77.0         36.3    608660.0  
12219         65.4         40.6     53007.0  
12220         65.4         40.6     53007.0  
12221         69.1         45.0    161791.0  
12222         69.1         45.0    161791.0  

[12223 rows x 9 columns]

In [37]:
house_list = []

for i in range(4000):
    if kmeans.predict(Xlist[i].reshape(1, -1)) == cat:
        print (housing_training_data.iloc[i])
        print (housing_training_data.house_id[i])
        house_list.append(housing_training_data.house_id[i])
        print (Xlist[i])
        print (kmeans.predict(Xlist[i].reshape(1, -1)))
        
    

house_id             1.0
price           369900.0
beds                 5.0
baths                3.0
square_feet       2500.0
lot_size        404672.0
hoa_permonth         0.0
Summer Temp         61.0
Winter Temp         19.0
population        1930.0
Name: 0, dtype: float64
1
[3.69900e+05 5.00000e+00 3.00000e+00 2.50000e+03 4.04672e+05 0.00000e+00
 6.10000e+01 1.90000e+01 1.93000e+03]
[131]
house_id             6.0
price           369000.0
beds                 4.0
baths                2.0
square_feet       2945.0
lot_size        384199.0
hoa_permonth         0.0
Summer Temp         61.0
Winter Temp         19.0
population        1930.0
Name: 5, dtype: float64
6
[3.69000e+05 4.00000e+00 2.00000e+00 2.94500e+03 3.84199e+05 0.00000e+00
 6.10000e+01 1.90000e+01 1.93000e+03]
[131]
house_id            12.0
price           324000.0
beds                 3.0
baths                3.0
square_feet       2824.0
lot_size        336283.0
hoa_permonth         0.0
Summer Temp         61.0
Winter Temp   

In [38]:
house_list

[1,
 6,
 12,
 15,
 16,
 24,
 353,
 473,
 568,
 633,
 706,
 725,
 750,
 784,
 851,
 901,
 914,
 1054,
 1339,
 2050]

In [39]:
house_data_for_results.head()

Unnamed: 0  house_id              property_type                address  \
0           0         1  Single Family Residential  32996 Heather Glen Ct   
1           1         2  Single Family Residential      70875 Lee Roy Ave   
2           2         3  Single Family Residential     26890 Sterling Hwy   
3           3         4  Single Family Residential     31513 Sterling Hwy   
4           4         5  Single Family Residential        72960 Laida Ave   

           city state zip_code     price  beds  baths  ...  lot_size  \
0  Anchor Point    AK  99556.0  369900.0   5.0    3.0  ...  404672.0   
1  Anchor Point    AK  99556.0  319000.0   2.0    2.0  ...  125452.0   
2  Anchor Point    AK  99556.0  115000.0   2.0    1.0  ...   86248.0   
3  Anchor Point    AK  99556.0  205000.0   3.0    1.0  ...   78408.0   
4  Anchor Point    AK  99556.0  299000.0   2.0    2.0  ...   78843.0   

   year_built hoa_permonth                                                url  \
0      2016.0          0.0  http://www.redfin.com/AK/Unknown/32996-HEATHER...   
1      2002.0          0.0  http://www.redfin.com/AK/Anchor-Point/70875-Le...   
2      2009.0          0.0  http://www.redfin.com/AK/Anchor-Point/26890-St...   
3      1962.0          0.0  http://www.redfin.com/AK/Anchor-Point/31513-St...   
4      1998.0          0.0  http://www.redfin.com/AK/Anchor-Point/72960-La...   

    latitude   longitude  Summer Temp  Winter Temp  population  pop_cat  
0  59.794550 -151.827787         61.0         19.0      1930.0    small  
1  59.845004 -151.787534         61.0         19.0      1930.0    small  
2  59.882706 -151.782732         61.0         19.0      1930.0    small  
3  59.816224 -151.827229         61.0         19.0      1930.0    small  
4  59.781840 -151.851596         61.0         19.0      1930.0    small  

[5 rows x 21 columns]

In [40]:
# house_list_test =  [1, 13, 43, 5643,357, 999]


In [42]:
results_df = house_data_for_results[house_data_for_results["house_id"].isin(house_list)]
results_df

Unnamed: 0  house_id              property_type                address  \
0              0         1  Single Family Residential  32996 Heather Glen Ct   
5              5         6  Single Family Residential       71185 Kutafya Rd   
11            11        12  Single Family Residential     26957 Sterling Hwy   
14            14        15  Single Family Residential       28160 Chestes Rd   
15            15        16  Single Family Residential    34614 North Fork Rd   
23            23        24  Single Family Residential        27155 Cloyds Rd   
352          352       353  Single Family Residential     52340 Sterling Hwy   
472          472       473  Single Family Residential          14845 Lobo Ln   
567          567       568  Single Family Residential  10703 S Old Glenn Hwy   
632          632       633  Single Family Residential         35250 James St   
705          705       706  Single Family Residential      38061 Tim Ross Rd   
724          724       725  Single Family Residential      26129 N Glenn Hwy   
749          749       750  Single Family Residential    1981 E Holobinko Rd   
783          783       784  Single Family Residential        2769 E Coles Rd   
850          850       851  Single Family Residential        3951 Wyoming Dr   
900          900       901  Single Family Residential     11759 N Maxwell Dr   
913          913       914  Single Family Residential   25445 Landlocked Ave   
1053        1053      1054  Single Family Residential   164 Naval Reserve Rd   
1338        1338      1339  Single Family Residential    5051 Old Moulton Rd   
2049        2049      2050  Single Family Residential    7854 Old Dixiana Rd   

              city state zip_code     price  beds  baths  ...  lot_size  \
0     Anchor Point    AK  99556.0  369900.0   5.0    3.0  ...  404672.0   
5     Anchor Point    AK  99556.0  369000.0   4.0    2.0  ...  384199.0   
11    Anchor Point    AK  99556.0  324000.0   3.0    3.0  ...  336283.0   
14    Anchor Point    AK  99556.0  324900.0   7.0    8.0  ...  394218.0   
15    Anchor Point    AK  99556.0  339500.0   1.0    1.0  ...  479160.0   
23    Anchor Point    AK  99556.0  204000.0   1.0    1.0  ...  470448.0   
352        Kasilof    AK  99610.0  165000.0   1.0    1.0  ...  653400.0   
472      Ninilchik    AK  99639.0  149500.0   2.0    1.0  ...  486129.0   
567         Palmer    AK  99645.0  324900.0   9.0    4.0  ...  409464.0   
632       Soldotna    AK  99669.0  189000.0   1.0    1.0  ...  395089.0   
705       Sterling    AK  99672.0  239000.0   2.0    2.0  ...  374616.0   
724         Sutton    AK  99674.0  375000.0   3.0    2.0  ...  525769.0   
749        Wasilla    AK  99654.0  315000.0   1.0    1.0  ...  434293.0   
783        Wasilla    AK  99654.0  374999.0   2.0    2.0  ...  417740.0   
850        Wasilla    AK  99623.0  371000.0   3.0    2.0  ...  423404.0   
900         Willow    AK  99688.0  450000.0   4.0    3.0  ...  548420.0   
913         Willow    AK  99688.0   99500.0   2.0    1.0  ...  377665.0   
1053      Bessemer    AL    35023  234900.0   3.0    2.0  ...  479160.0   
1338       Decatur    AL    35603  179900.0   3.0    1.0  ...  479160.0   
2049        Pinson    AL    35123  120000.0   2.0    2.0  ...  435600.0   

      year_built hoa_permonth  \
0         2016.0          0.0   
5         1983.0          0.0   
11        1986.0          0.0   
14        2002.0          0.0   
15        1994.0          0.0   
23        1999.0          0.0   
352       2016.0          0.0   
472       1990.0          0.0   
567       1966.0          0.0   
632       1985.0          0.0   
705       2008.0          0.0   
724       1972.0          0.0   
749       1975.0          0.0   
783       1993.0          0.0   
850       2020.0          0.0   
900       1995.0          0.0   
913       2016.0          0.0   
1053      1930.0          0.0   
1338      1958.0          0.0   
2049      1965.0          0.0   

                                                    url

In [43]:
results_df.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Unnamed: 0</th>\n      <th>house_id</th>\n      <th>property_type</th>\n      <th>address</th>\n      <th>city</th>\n      <th>state</th>\n      <th>zip_code</th>\n      <th>price</th>\n      <th>beds</th>\n      <th>baths</th>\n      <th>square_feet</th>\n      <th>lot_size</th>\n      <th>year_built</th>\n      <th>hoa_permonth</th>\n      <th>url</th>\n      <th>latitude</th>\n      <th>longitude</th>\n      <th>Summer Temp</th>\n      <th>Winter Temp</th>\n      <th>population</th>\n      <th>pop_cat</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>1</td>\n      <td>Single Family Residential</td>\n      <td>32996 Heather Glen Ct</td>\n      <td>Anchor Point</td>\n      <td>AK</td>\n      <td>99556.0</td>\n      <td>369900.0</td>\n      <td>5.0</td>\n      <td>3.0</td>\n      <td>2500.0</td>\n      <td>404672.0</td>\n      <